# Generated by Django 6.0.2 on 2026-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="monthly_savings",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
